  #-------------- file test.conf --------------
#TYPE:imageMNSTR:me myself iPASS:passPAGE:http://www.networksplus.net/n0nb/fork/dampep.htmlSRC:http://www.networksplus.net/n0nb/fork/boltjig.jpgKEYID:1
#TYPE:render_txtMNSTR:me myself iPASS:passPAGE:noneSRC:noneKEYID:noneRETYP:none
#TYPE:render_baseMNSTR:me_myself_iPASS:passPAGE:noneSRC:noneKEYID:noneRETYP:none
#TYPE:txt_to_baseMNSTR:me_myself_iPASS:passPAGE:noneSRC:noneKEYID:noneRETYP:none
# telnet 127.0.0.1 20204

# mencoder mf://*.png type=png:w=800:h=600:fps=25 -ovc copy -o output_t.avi 
#TYPE:render_baseMNSTR:AluminiumPASS:passPAGE:noneSRC:noneKEYID:noneRETYP:none
#
# 


  ### user and group to become
  user        harwood

  group       admin

  ### logging ?
  log_file    /home/harwood/Desktop/server.log
  log_level   4
  pid_file    /tmp/server.pid

  ### optional syslog directive:qa
  #
  ### used in place of log_file above
  #log_file       Sys::Syslog
  #syslog_logsock unix
  #syslog_ident   myserver
  #syslog_logopt  pid|cons

  ### access control
  allow       .+\.(net|com)
  allow       domain\.com
  deny        a.+
  cidr_allow  127.0.0.0/8
  cidr_allow  192.0.2.0/24
  cidr_deny   192.0.2.4/30

  ### background the process?
  background  0

  ### ports to bind (this should bind
  ### 127.0.0.1:20205 and localhost:20204)
  ### See Net::Server::Proto
  host        127.0.0.1
  port        localhost:20204
  port        20205

  ### reverse lookups ?
  # reverse_lookups on
#check_for_dead 120
max_servers 1
#max_dequeue 256
#check_for_dequeue 15

  #-------------- file test.conf --------------# for more sample parameters.
